[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vm_single_choice = "2noSBsEGTG9CY2cdCj7Z6oPj8L62fr4yq8pMPPagRdCY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hieu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
